Rscript evaluate_models_constantthreshold.R 1 &
Rscript evaluate_models_constantthreshold.R 6 &
Rscript evaluate_models_constantthreshold.R 11 &
Rscript evaluate_models_constantthreshold.R 16 &
Rscript evaluate_models_constantthreshold.R 21 &
Rscript evaluate_models_constantthreshold.R 26 &
Rscript evaluate_models_constantthreshold.R 31 &
Rscript evaluate_models_constantthreshold.R 36 &
Rscript evaluate_models_constantthreshold.R 41 &
Rscript evaluate_models_constantthreshold.R 46 &
Rscript evaluate_models_constantthreshold.R 51 &
Rscript evaluate_models_constantthreshold.R 56 &
Rscript evaluate_models_constantthreshold.R 61 &
Rscript evaluate_models_constantthreshold.R 66 &
Rscript evaluate_models_constantthreshold.R 71 &
Rscript evaluate_models_constantthreshold.R 76 &
Rscript evaluate_models_constantthreshold.R 81 &
Rscript evaluate_models_constantthreshold.R 86 &
Rscript evaluate_models_constantthreshold.R 91 &
Rscript evaluate_models_constantthreshold.R 96 &
Rscript evaluate_models_constantthreshold.R 101 &
Rscript evaluate_models_constantthreshold.R 106 &
Rscript evaluate_models_constantthreshold.R 111 &
Rscript evaluate_models_constantthreshold.R 116 &
Rscript evaluate_models_constantthreshold.R 121 &
Rscript evaluate_models_constantthreshold.R 126
