Rscript run_maxent_and_evaluate_models.R 1 &
Rscript run_maxent_and_evaluate_models.R 6 &
Rscript run_maxent_and_evaluate_models.R 11 &
Rscript run_maxent_and_evaluate_models.R 16 &
Rscript run_maxent_and_evaluate_models.R 21 &
Rscript run_maxent_and_evaluate_models.R 26 &
Rscript run_maxent_and_evaluate_models.R 31 &
Rscript run_maxent_and_evaluate_models.R 36 &
Rscript run_maxent_and_evaluate_models.R 41 &
Rscript run_maxent_and_evaluate_models.R 46 &
Rscript run_maxent_and_evaluate_models.R 51 &
Rscript run_maxent_and_evaluate_models.R 56 &
Rscript run_maxent_and_evaluate_models.R 61 &
Rscript run_maxent_and_evaluate_models.R 66 &
Rscript run_maxent_and_evaluate_models.R 71 &
Rscript run_maxent_and_evaluate_models.R 76 &
Rscript run_maxent_and_evaluate_models.R 81 &
Rscript run_maxent_and_evaluate_models.R 86 &
Rscript run_maxent_and_evaluate_models.R 91 &
Rscript run_maxent_and_evaluate_models.R 96 &
Rscript run_maxent_and_evaluate_models.R 101 &
Rscript run_maxent_and_evaluate_models.R 106 &
Rscript run_maxent_and_evaluate_models.R 111 &
Rscript run_maxent_and_evaluate_models.R 116 &
Rscript run_maxent_and_evaluate_models.R 121